# Generated by Django 6.0.6 on 2026-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='access_pin',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
