# Generated by Django 6.0.6 on 2026-07-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_customer_name_remove_invoice_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.slot'),
        ),
    ]
