# Generated by Django 6.0.6 on 2026-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_access_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='customer_qr/'),
        ),
    ]
