# Generated by Django 6.0.6 on 2026-07-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='billing.customer'),
        ),
    ]
