"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-94tc6dcq&_rdp*#)07%1r3ejh#)=gw47p=tu$7qqb@58ug)34^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [   
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "unfold.contrib.hijack",  # optional, if django-hijack package is used
    'django_tenants',
    'tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'config',
    'billing',
]


SHARED_APPS = [
    'django.contrib.auth',        
    'django_tenants',
    'tenants',
    'django.contrib.admin',       
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.sessions',    
    'django.contrib.messages',
]

TENANT_APPS = [
    # apps that live INSIDE each tenant's schema
    'django.contrib.auth',     
    'billing',
    'django.contrib.admin',       
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.sessions',    
    'django.contrib.messages',
]

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)





MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'royaltyapp',
        'USER': 'parth',
        'PASSWORD': 'parth@123',
        'HOST': 'localhost',  # Or your remote database IP
        'PORT': '5432'
    }
}

"""  """
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',   # ← gives you the testable HTML UI
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # needed for browsable UI login
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',
    },
}


CSRF_TRUSTED_ORIGINS = [
    'https://localhost.com',
    'https://*.localhost.com',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://*.localhost:8000',     
    'http://.localhost:8000',    
]



import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TENANT_MODEL = "tenants.Client"
TENANT_DOMAIN_MODEL = "tenants.Domain"


ROOT_URLCONF = 'config.urls_public'          
PUBLIC_SCHEMA_URLCONF = 'config.urls_public' 
TENANT_URLCONF = 'config.urls_tenants'


SESSION_COOKIE_DOMAIN = None   # let the browser handle it per-subdomain automatically
CSRF_COOKIE_DOMAIN = None

# settings.py

# UNFOLD = {
#     "SIDEBAR": {
#         "show_search": True,
#         "navigation": [
#             {
#                 "title": "Tenant Management (Public Only)",
#                 "separator": True,
#                 "items": [
#                     {
#                         "title": "Clients",
#                         "icon": "business",
#                         "link": "admin:tenants_client_changelist",
#                     },
#                     {
#                         "title": "Domains",
#                         "icon": "language",
#                         "link": "admin:tenants_domain_changelist",
#                     },
#                 ],
#             },
#             # {
#             #     "title": "Billing & Apps (Tenant Only)",
#             #     "separator": True,
#             #     "items": [
#             #         {
#             #             "title": "Customers",
#             #             "icon": "group",
#             #             "link": "admin:billing_customer_changelist",
#             #         },
#             #         {
#             #             "title": "Invoices",
#             #             "icon": "receipt",
#             #             "link": "admin:billing_invoice_changelist",
#             #         },
#             #         {
#             #             "title": "Slots",
#             #             "icon": "schedule",
#             #             "link": "admin:billing_slot_changelist",
#             #         },
#             #     ],
#             # },
#         ],
#     },
# }